export const SERVICE_CATEGORY_PRESETS = [
  "Cabelo feminino",
  "Cabelo masculino",
  "Coloração",
  "Escova e finalização",
  "Barba",
  "Manicure",
  "Pedicure",
  "Unhas em gel",
  "Sobrancelhas",
  "Cílios",
  "Maquiagem",
  "Depilação",
  "Limpeza de pele",
  "Estética facial",
  "Estética corporal",
  "Massagem",
  "Spa e relaxamento",
  "Podologia",
] as const;
