/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard.appointments'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBirthdaysRouteImport } from './routes/dashboard.birthdays'
import { Route as DashboardClientAppRouteImport } from './routes/dashboard.client-app'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardFeedRouteImport } from './routes/dashboard.feed'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard.subscriptions'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardAiIndexRouteImport } from './routes/dashboard.ai.index'
import { Route as DashboardAiExportRouteImport } from './routes/dashboard.ai.export'
import { Route as DashboardBenefitsIndexRouteImport } from './routes/dashboard.benefits.index'
import { Route as DashboardBenefitsAutomationsRouteImport } from './routes/dashboard.benefits.automations'
import { Route as DashboardBenefitsLoyaltyRouteImport } from './routes/dashboard.benefits.loyalty'
import { Route as DashboardBenefitsPromotionsRouteImport } from './routes/dashboard.benefits.promotions'
import { Route as DashboardBenefitsReferralsRouteImport } from './routes/dashboard.benefits.referrals'
import { Route as DashboardFinanceIndexRouteImport } from './routes/dashboard.finance.index'
import { Route as DashboardFinanceDespesasRouteImport } from './routes/dashboard.finance.despesas'
import { Route as DashboardGestaoClientesRouteImport } from './routes/dashboard.gestao.clientes'
import { Route as DashboardGestaoComissoesRouteImport } from './routes/dashboard.gestao.comissoes'
import { Route as DashboardGestaoPagamentosRouteImport } from './routes/dashboard.gestao.pagamentos'
import { Route as DashboardGestaoProfissionaisRouteImport } from './routes/dashboard.gestao.profissionais'
import { Route as DashboardGestaoServicosRouteImport } from './routes/dashboard.gestao.servicos'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard.notifications.index'
import { Route as DashboardNotificationsExportRouteImport } from './routes/dashboard.notifications.export'
import { Route as DashboardOperationsIndexRouteImport } from './routes/dashboard.operations.index'
import { Route as DashboardOperationsComandasRouteImport } from './routes/dashboard.operations.comandas'
import { Route as DashboardGestaoAgendamentosIndexRouteImport } from './routes/dashboard.gestao.agendamentos.index'
import { Route as DashboardGestaoAgendamentosInteligenteRouteImport } from './routes/dashboard.gestao.agendamentos.inteligente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBirthdaysRoute = DashboardBirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientAppRoute = DashboardClientAppRouteImport.update({
  id: '/client-app',
  path: '/client-app',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeedRoute = DashboardFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiIndexRoute = DashboardAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiExportRoute = DashboardAiExportRouteImport.update({
  id: '/ai/export',
  path: '/ai/export',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBenefitsIndexRoute = DashboardBenefitsIndexRouteImport.update({
  id: '/benefits/',
  path: '/benefits/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBenefitsAutomationsRoute =
  DashboardBenefitsAutomationsRouteImport.update({
    id: '/benefits/automations',
    path: '/benefits/automations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBenefitsLoyaltyRoute =
  DashboardBenefitsLoyaltyRouteImport.update({
    id: '/benefits/loyalty',
    path: '/benefits/loyalty',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBenefitsPromotionsRoute =
  DashboardBenefitsPromotionsRouteImport.update({
    id: '/benefits/promotions',
    path: '/benefits/promotions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBenefitsReferralsRoute =
  DashboardBenefitsReferralsRouteImport.update({
    id: '/benefits/referrals',
    path: '/benefits/referrals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceDespesasRoute =
  DashboardFinanceDespesasRouteImport.update({
    id: '/finance/despesas',
    path: '/finance/despesas',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGestaoClientesRoute = DashboardGestaoClientesRouteImport.update({
  id: '/gestao/clientes',
  path: '/gestao/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGestaoComissoesRoute =
  DashboardGestaoComissoesRouteImport.update({
    id: '/gestao/comissoes',
    path: '/gestao/comissoes',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGestaoPagamentosRoute =
  DashboardGestaoPagamentosRouteImport.update({
    id: '/gestao/pagamentos',
    path: '/gestao/pagamentos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGestaoProfissionaisRoute =
  DashboardGestaoProfissionaisRouteImport.update({
    id: '/gestao/profissionais',
    path: '/gestao/profissionais',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGestaoServicosRoute = DashboardGestaoServicosRouteImport.update({
  id: '/gestao/servicos',
  path: '/gestao/servicos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardNotificationsExportRoute =
  DashboardNotificationsExportRouteImport.update({
    id: '/notifications/export',
    path: '/notifications/export',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOperationsIndexRoute =
  DashboardOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOperationsComandasRoute =
  DashboardOperationsComandasRouteImport.update({
    id: '/operations/comandas',
    path: '/operations/comandas',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGestaoAgendamentosIndexRoute =
  DashboardGestaoAgendamentosIndexRouteImport.update({
    id: '/gestao/agendamentos/',
    path: '/gestao/agendamentos/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGestaoAgendamentosInteligenteRoute =
  DashboardGestaoAgendamentosInteligenteRouteImport.update({
    id: '/gestao/agendamentos/inteligente',
    path: '/gestao/agendamentos/inteligente',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/client-app': typeof DashboardClientAppRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/feed': typeof DashboardFeedRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai/export': typeof DashboardAiExportRoute
  '/dashboard/benefits/automations': typeof DashboardBenefitsAutomationsRoute
  '/dashboard/benefits/loyalty': typeof DashboardBenefitsLoyaltyRoute
  '/dashboard/benefits/promotions': typeof DashboardBenefitsPromotionsRoute
  '/dashboard/benefits/referrals': typeof DashboardBenefitsReferralsRoute
  '/dashboard/finance/despesas': typeof DashboardFinanceDespesasRoute
  '/dashboard/gestao/clientes': typeof DashboardGestaoClientesRoute
  '/dashboard/gestao/comissoes': typeof DashboardGestaoComissoesRoute
  '/dashboard/gestao/pagamentos': typeof DashboardGestaoPagamentosRoute
  '/dashboard/gestao/profissionais': typeof DashboardGestaoProfissionaisRoute
  '/dashboard/gestao/servicos': typeof DashboardGestaoServicosRoute
  '/dashboard/notifications/export': typeof DashboardNotificationsExportRoute
  '/dashboard/operations/comandas': typeof DashboardOperationsComandasRoute
  '/dashboard/ai/': typeof DashboardAiIndexRoute
  '/dashboard/benefits/': typeof DashboardBenefitsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/gestao/agendamentos/inteligente': typeof DashboardGestaoAgendamentosInteligenteRoute
  '/dashboard/gestao/agendamentos/': typeof DashboardGestaoAgendamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/client-app': typeof DashboardClientAppRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/feed': typeof DashboardFeedRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ai/export': typeof DashboardAiExportRoute
  '/dashboard/benefits/automations': typeof DashboardBenefitsAutomationsRoute
  '/dashboard/benefits/loyalty': typeof DashboardBenefitsLoyaltyRoute
  '/dashboard/benefits/promotions': typeof DashboardBenefitsPromotionsRoute
  '/dashboard/benefits/referrals': typeof DashboardBenefitsReferralsRoute
  '/dashboard/finance/despesas': typeof DashboardFinanceDespesasRoute
  '/dashboard/gestao/clientes': typeof DashboardGestaoClientesRoute
  '/dashboard/gestao/comissoes': typeof DashboardGestaoComissoesRoute
  '/dashboard/gestao/pagamentos': typeof DashboardGestaoPagamentosRoute
  '/dashboard/gestao/profissionais': typeof DashboardGestaoProfissionaisRoute
  '/dashboard/gestao/servicos': typeof DashboardGestaoServicosRoute
  '/dashboard/notifications/export': typeof DashboardNotificationsExportRoute
  '/dashboard/operations/comandas': typeof DashboardOperationsComandasRoute
  '/dashboard/ai': typeof DashboardAiIndexRoute
  '/dashboard/benefits': typeof DashboardBenefitsIndexRoute
  '/dashboard/finance': typeof DashboardFinanceIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/operations': typeof DashboardOperationsIndexRoute
  '/dashboard/gestao/agendamentos/inteligente': typeof DashboardGestaoAgendamentosInteligenteRoute
  '/dashboard/gestao/agendamentos': typeof DashboardGestaoAgendamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/client-app': typeof DashboardClientAppRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/feed': typeof DashboardFeedRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai/export': typeof DashboardAiExportRoute
  '/dashboard/benefits/automations': typeof DashboardBenefitsAutomationsRoute
  '/dashboard/benefits/loyalty': typeof DashboardBenefitsLoyaltyRoute
  '/dashboard/benefits/promotions': typeof DashboardBenefitsPromotionsRoute
  '/dashboard/benefits/referrals': typeof DashboardBenefitsReferralsRoute
  '/dashboard/finance/despesas': typeof DashboardFinanceDespesasRoute
  '/dashboard/gestao/clientes': typeof DashboardGestaoClientesRoute
  '/dashboard/gestao/comissoes': typeof DashboardGestaoComissoesRoute
  '/dashboard/gestao/pagamentos': typeof DashboardGestaoPagamentosRoute
  '/dashboard/gestao/profissionais': typeof DashboardGestaoProfissionaisRoute
  '/dashboard/gestao/servicos': typeof DashboardGestaoServicosRoute
  '/dashboard/notifications/export': typeof DashboardNotificationsExportRoute
  '/dashboard/operations/comandas': typeof DashboardOperationsComandasRoute
  '/dashboard/ai/': typeof DashboardAiIndexRoute
  '/dashboard/benefits/': typeof DashboardBenefitsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/gestao/agendamentos/inteligente': typeof DashboardGestaoAgendamentosInteligenteRoute
  '/dashboard/gestao/agendamentos/': typeof DashboardGestaoAgendamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/birthdays'
    | '/dashboard/client-app'
    | '/dashboard/customers'
    | '/dashboard/feed'
    | '/dashboard/inventory'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/ai/export'
    | '/dashboard/benefits/automations'
    | '/dashboard/benefits/loyalty'
    | '/dashboard/benefits/promotions'
    | '/dashboard/benefits/referrals'
    | '/dashboard/finance/despesas'
    | '/dashboard/gestao/clientes'
    | '/dashboard/gestao/comissoes'
    | '/dashboard/gestao/pagamentos'
    | '/dashboard/gestao/profissionais'
    | '/dashboard/gestao/servicos'
    | '/dashboard/notifications/export'
    | '/dashboard/operations/comandas'
    | '/dashboard/ai/'
    | '/dashboard/benefits/'
    | '/dashboard/finance/'
    | '/dashboard/notifications/'
    | '/dashboard/operations/'
    | '/dashboard/gestao/agendamentos/inteligente'
    | '/dashboard/gestao/agendamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/birthdays'
    | '/dashboard/client-app'
    | '/dashboard/customers'
    | '/dashboard/feed'
    | '/dashboard/inventory'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/team'
    | '/dashboard'
    | '/dashboard/ai/export'
    | '/dashboard/benefits/automations'
    | '/dashboard/benefits/loyalty'
    | '/dashboard/benefits/promotions'
    | '/dashboard/benefits/referrals'
    | '/dashboard/finance/despesas'
    | '/dashboard/gestao/clientes'
    | '/dashboard/gestao/comissoes'
    | '/dashboard/gestao/pagamentos'
    | '/dashboard/gestao/profissionais'
    | '/dashboard/gestao/servicos'
    | '/dashboard/notifications/export'
    | '/dashboard/operations/comandas'
    | '/dashboard/ai'
    | '/dashboard/benefits'
    | '/dashboard/finance'
    | '/dashboard/notifications'
    | '/dashboard/operations'
    | '/dashboard/gestao/agendamentos/inteligente'
    | '/dashboard/gestao/agendamentos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/birthdays'
    | '/dashboard/client-app'
    | '/dashboard/customers'
    | '/dashboard/feed'
    | '/dashboard/inventory'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/ai/export'
    | '/dashboard/benefits/automations'
    | '/dashboard/benefits/loyalty'
    | '/dashboard/benefits/promotions'
    | '/dashboard/benefits/referrals'
    | '/dashboard/finance/despesas'
    | '/dashboard/gestao/clientes'
    | '/dashboard/gestao/comissoes'
    | '/dashboard/gestao/pagamentos'
    | '/dashboard/gestao/profissionais'
    | '/dashboard/gestao/servicos'
    | '/dashboard/notifications/export'
    | '/dashboard/operations/comandas'
    | '/dashboard/ai/'
    | '/dashboard/benefits/'
    | '/dashboard/finance/'
    | '/dashboard/notifications/'
    | '/dashboard/operations/'
    | '/dashboard/gestao/agendamentos/inteligente'
    | '/dashboard/gestao/agendamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/birthdays': {
      id: '/dashboard/birthdays'
      path: '/birthdays'
      fullPath: '/dashboard/birthdays'
      preLoaderRoute: typeof DashboardBirthdaysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-app': {
      id: '/dashboard/client-app'
      path: '/client-app'
      fullPath: '/dashboard/client-app'
      preLoaderRoute: typeof DashboardClientAppRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feed': {
      id: '/dashboard/feed'
      path: '/feed'
      fullPath: '/dashboard/feed'
      preLoaderRoute: typeof DashboardFeedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai/': {
      id: '/dashboard/ai/'
      path: '/ai'
      fullPath: '/dashboard/ai/'
      preLoaderRoute: typeof DashboardAiIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai/export': {
      id: '/dashboard/ai/export'
      path: '/ai/export'
      fullPath: '/dashboard/ai/export'
      preLoaderRoute: typeof DashboardAiExportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benefits/': {
      id: '/dashboard/benefits/'
      path: '/benefits'
      fullPath: '/dashboard/benefits/'
      preLoaderRoute: typeof DashboardBenefitsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benefits/automations': {
      id: '/dashboard/benefits/automations'
      path: '/benefits/automations'
      fullPath: '/dashboard/benefits/automations'
      preLoaderRoute: typeof DashboardBenefitsAutomationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benefits/loyalty': {
      id: '/dashboard/benefits/loyalty'
      path: '/benefits/loyalty'
      fullPath: '/dashboard/benefits/loyalty'
      preLoaderRoute: typeof DashboardBenefitsLoyaltyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benefits/promotions': {
      id: '/dashboard/benefits/promotions'
      path: '/benefits/promotions'
      fullPath: '/dashboard/benefits/promotions'
      preLoaderRoute: typeof DashboardBenefitsPromotionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benefits/referrals': {
      id: '/dashboard/benefits/referrals'
      path: '/benefits/referrals'
      fullPath: '/dashboard/benefits/referrals'
      preLoaderRoute: typeof DashboardBenefitsReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance/': {
      id: '/dashboard/finance/'
      path: '/finance'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance/despesas': {
      id: '/dashboard/finance/despesas'
      path: '/finance/despesas'
      fullPath: '/dashboard/finance/despesas'
      preLoaderRoute: typeof DashboardFinanceDespesasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/clientes': {
      id: '/dashboard/gestao/clientes'
      path: '/gestao/clientes'
      fullPath: '/dashboard/gestao/clientes'
      preLoaderRoute: typeof DashboardGestaoClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/comissoes': {
      id: '/dashboard/gestao/comissoes'
      path: '/gestao/comissoes'
      fullPath: '/dashboard/gestao/comissoes'
      preLoaderRoute: typeof DashboardGestaoComissoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/pagamentos': {
      id: '/dashboard/gestao/pagamentos'
      path: '/gestao/pagamentos'
      fullPath: '/dashboard/gestao/pagamentos'
      preLoaderRoute: typeof DashboardGestaoPagamentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/profissionais': {
      id: '/dashboard/gestao/profissionais'
      path: '/gestao/profissionais'
      fullPath: '/dashboard/gestao/profissionais'
      preLoaderRoute: typeof DashboardGestaoProfissionaisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/servicos': {
      id: '/dashboard/gestao/servicos'
      path: '/gestao/servicos'
      fullPath: '/dashboard/gestao/servicos'
      preLoaderRoute: typeof DashboardGestaoServicosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications/export': {
      id: '/dashboard/notifications/export'
      path: '/notifications/export'
      fullPath: '/dashboard/notifications/export'
      preLoaderRoute: typeof DashboardNotificationsExportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operations/': {
      id: '/dashboard/operations/'
      path: '/operations'
      fullPath: '/dashboard/operations/'
      preLoaderRoute: typeof DashboardOperationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operations/comandas': {
      id: '/dashboard/operations/comandas'
      path: '/operations/comandas'
      fullPath: '/dashboard/operations/comandas'
      preLoaderRoute: typeof DashboardOperationsComandasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/agendamentos/': {
      id: '/dashboard/gestao/agendamentos/'
      path: '/gestao/agendamentos'
      fullPath: '/dashboard/gestao/agendamentos/'
      preLoaderRoute: typeof DashboardGestaoAgendamentosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gestao/agendamentos/inteligente': {
      id: '/dashboard/gestao/agendamentos/inteligente'
      path: '/gestao/agendamentos/inteligente'
      fullPath: '/dashboard/gestao/agendamentos/inteligente'
      preLoaderRoute: typeof DashboardGestaoAgendamentosInteligenteRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBirthdaysRoute: typeof DashboardBirthdaysRoute
  DashboardClientAppRoute: typeof DashboardClientAppRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardFeedRoute: typeof DashboardFeedRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAiExportRoute: typeof DashboardAiExportRoute
  DashboardBenefitsAutomationsRoute: typeof DashboardBenefitsAutomationsRoute
  DashboardBenefitsLoyaltyRoute: typeof DashboardBenefitsLoyaltyRoute
  DashboardBenefitsPromotionsRoute: typeof DashboardBenefitsPromotionsRoute
  DashboardBenefitsReferralsRoute: typeof DashboardBenefitsReferralsRoute
  DashboardFinanceDespesasRoute: typeof DashboardFinanceDespesasRoute
  DashboardGestaoClientesRoute: typeof DashboardGestaoClientesRoute
  DashboardGestaoComissoesRoute: typeof DashboardGestaoComissoesRoute
  DashboardGestaoPagamentosRoute: typeof DashboardGestaoPagamentosRoute
  DashboardGestaoProfissionaisRoute: typeof DashboardGestaoProfissionaisRoute
  DashboardGestaoServicosRoute: typeof DashboardGestaoServicosRoute
  DashboardNotificationsExportRoute: typeof DashboardNotificationsExportRoute
  DashboardOperationsComandasRoute: typeof DashboardOperationsComandasRoute
  DashboardAiIndexRoute: typeof DashboardAiIndexRoute
  DashboardBenefitsIndexRoute: typeof DashboardBenefitsIndexRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardOperationsIndexRoute: typeof DashboardOperationsIndexRoute
  DashboardGestaoAgendamentosInteligenteRoute: typeof DashboardGestaoAgendamentosInteligenteRoute
  DashboardGestaoAgendamentosIndexRoute: typeof DashboardGestaoAgendamentosIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBirthdaysRoute: DashboardBirthdaysRoute,
  DashboardClientAppRoute: DashboardClientAppRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardFeedRoute: DashboardFeedRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAiExportRoute: DashboardAiExportRoute,
  DashboardBenefitsAutomationsRoute: DashboardBenefitsAutomationsRoute,
  DashboardBenefitsLoyaltyRoute: DashboardBenefitsLoyaltyRoute,
  DashboardBenefitsPromotionsRoute: DashboardBenefitsPromotionsRoute,
  DashboardBenefitsReferralsRoute: DashboardBenefitsReferralsRoute,
  DashboardFinanceDespesasRoute: DashboardFinanceDespesasRoute,
  DashboardGestaoClientesRoute: DashboardGestaoClientesRoute,
  DashboardGestaoComissoesRoute: DashboardGestaoComissoesRoute,
  DashboardGestaoPagamentosRoute: DashboardGestaoPagamentosRoute,
  DashboardGestaoProfissionaisRoute: DashboardGestaoProfissionaisRoute,
  DashboardGestaoServicosRoute: DashboardGestaoServicosRoute,
  DashboardNotificationsExportRoute: DashboardNotificationsExportRoute,
  DashboardOperationsComandasRoute: DashboardOperationsComandasRoute,
  DashboardAiIndexRoute: DashboardAiIndexRoute,
  DashboardBenefitsIndexRoute: DashboardBenefitsIndexRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardOperationsIndexRoute: DashboardOperationsIndexRoute,
  DashboardGestaoAgendamentosInteligenteRoute:
    DashboardGestaoAgendamentosInteligenteRoute,
  DashboardGestaoAgendamentosIndexRoute: DashboardGestaoAgendamentosIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
